letter = Letter.create!(letter_number: "001")
letter.records.create!(name: "First Name 05", unit_price: 29.95, quantity: 1, template: "aip1")
letter = Letter.create!(letter_number: "002")
letter.records.create!(name: "First Name 06", unit_price: 24.99, quantity: 2, template: "aip1")
letter = Letter.create!(letter_number: "003")
letter.records.create!(name: "First Name 07", unit_price: 9.00, quantity: 1, template: "aip1")
letter = Letter.create!(letter_number: "004")
letter.records.create!(name: "First Name 08", unit_price: 1955.00, quantity: 1, template: "aip1")
letter = Letter.create!(letter_number: "005")
letter.records.create!(name: "First Name 09", unit_price: 75.00, quantity: 3, template: "aip1")
letter = Letter.create!(letter_number:  "006")
letter.records.create!(name: "First Last Name 1", unit_price: 10000.00, quantity: 1, template: "aip2")
letter = Letter.create!(letter_number: "007")
letter.records.create!(name: "First Last Name 2", unit_price: 8450.00, quantity: 1, template: "aip2")
letter = Letter.create!(letter_number: "008")
letter.records.create!(name: "First Last Name 3", unit_price: 10000.00, quantity: 1, template: "aip2")
letter = Letter.create!(letter_number: "009")
letter.records.create!(name: "First Last Name 4", unit_price: 8450.00, quantity: 1, template: "aip2")

