letter = Letter.create!(letter_number: "001")
letter.line_items.create!(name: "Settlers of Catan", unit_price: 29.95, quantity: 1, template: "aip1")
letter = Letter.create!(letter_number: "002")
letter.line_items.create!(name: "Technodrome", unit_price: 24.99, quantity: 2, template: "aip1")
letter = Letter.create!(letter_number: "003")
letter.line_items.create!(name: "RailsCasts Pro Subscription", unit_price: 9.00, quantity: 1, template: "aip1")
letter = Letter.create!(letter_number: "004")
letter.line_items.create!(name: "Flux Capacitor", unit_price: 1955.00, quantity: 1, template: "aip1")
letter = Letter.create!(letter_number: "005")
letter.line_items.create!(name: "TextMate 2", unit_price: 75.00, quantity: 3, template: "aip1")
letter = Letter.create!(letter_number:  "006")
letter.line_items.create!(name: "First Last Name 1", unit_price: 10000.00, quantity: 1, template: "aip2")
letter = Letter.create!(letter_number: "007")
letter.line_items.create!(name: "First Last Name 2", unit_price: 8450.00, quantity: 1, template: "aip2")
letter = Letter.create!(letter_number: "008")
letter.line_items.create!(name: "First Last Name 3", unit_price: 10000.00, quantity: 1, template: "aip2")
letter = Letter.create!(letter_number: "009")
letter.line_items.create!(name: "First Last Name 4", unit_price: 8450.00, quantity: 1, template: "aip2")